spring:
  application:
    name: my-city-gov

  datasource:
    url: jdbc:postgresql://dpg-d5gj40khg0os73bm3880-a.frankfurt-postgres.render.com:5432/mycitygovdb_g4xk
    username: mycitygovusr
    password: IkruZ7mJ83PdLGRz2uQFrthlOyjHwVPO
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  web:
    error:
      whitelabel:
        enabled: false
      include-message: always
      include-binding-errors: always
      include-exception: true

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: request-files

jwt:
  secret: "${JWT_SECRET:PfgUTsmk6KRec9PefUUtu9AMXKJRoub1geat2KKW1FY=}"
  issuer: "my-city-gov-api"
  audience: "external-systems"
  ttl-minutes: 60

nocgov:
  base-url: http://localhost:8081/api/v1/person

nocsms:
  base-url: http://localhost:8082/api/v1/sms
