services:
  postgres:
    image: postgres:16
    container_name: nocgov-postgres
    restart: always
    environment:
      POSTGRES_DB: nocgovdb
      POSTGRES_USER: nocgovuser
      POSTGRES_PASSWORD: nocgovpassword
    ports:
      - "5433:5432"
    volumes:
      - nocgov_postgres_data:/var/lib/postgresql/data

volumes:
  nocgov_postgres_data:
